### ISSUE TITLE
can handle other RD60nnx power supplies

### ISSUE THREAD

**Issue by doug-gilbert** [Serge78rus/rd6006p#1]
I have a RD6006P and a RD6018 for heavy lifting. This utility works as advertised for the RD6006p which is great. Tried it on my RD6018 and it looks close, out by a factor of 100. My RD6018 is set for 15 Volts output and my DUT is pulling 70 mA. Below is what I see:

./rd6006p -d /dev/ttyUSB1 -b 115200 -i
Device information
	Type:        UNKNOWN (0)
	Serial:      0000000xxx
	FW version:  1.36
	Temperature: 20°C

CV 1.499 0.0007
CV 1.499 0.0007
...

To handle this you might create a hard link to rd6006p called rd6018 (maybe also rd6006). Then your code can look at argv[0] to find out the name it was invoked by, then tweak the numbers accordingly.

**Comment by Serge78rus** [comment]
Out of the entire RD60XX family, I have only RD6006P. Since I do not have the opportunity to check the operation with other devices, I limited myself to this.
